import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Biccas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <main>
            <Navbar />
            <div className="max-w-[1440px] m-auto p-4">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
